<?php

	namespace umono\multiple\controllers;

	use umono\multiple\interceptor\HttpHeaderAuth;
	use yii\filters\ContentNegotiator;
	use yii\filters\Cors;
	use yii\filters\RateLimiter;
	use yii\filters\VerbFilter;
	use yii\web\Response;

	class AdminController extends ApiController
	{
		public function behaviors()
		{
			return [
				'content' => [
					'class'   => ContentNegotiator::class,
					'formats' => [
						'application/json' => Response::FORMAT_JSON,
					],
				],
				'cors'    => [
					'class' => Cors::class,
					'cors'  => [
						'Origin'                           => ['*'],
						'Access-Control-Request-Method'    => [
							'GET',
							'POST',
							'PUT',
							'PATCH',
							'DELETE',
							'HEAD',
							'OPTIONS',
						],
						'Access-Control-Request-Headers'   => ['*'],
						'Access-Control-Allow-Credentials' => null,
						'Access-Control-Max-Age'           => 86400,
						'Access-Control-Expose-Headers'    => [
							'X-Suggested-Filename',
						],
					],
				],
				'verb'    => [
					'class'   => VerbFilter::class,
					'actions' => $this->verbs(),
				],
				'auth'    => [
					'class'    => HttpHeaderAuth::class,
					'header'   => 'X-Access-Token',
					'clientId' => $this->getClientId(),
					'optional' => [
						'auth/login',
						'auth/phone-login',
						'auth/get-code',
						'auth/logout',
						'auth/scan',
						'test/*',
					],
				],
				'access'  => [
					'class'  => AccessControl::class,
					'except' => [
						'auth/login',
						'auth/phone-login',
						'auth/get-code',
						'auth/logout',
						'auth/scan',
						'test/*',
					],
				],
				'rate'    => [
					'class' => RateLimiter::class,
				],
			];
		}

		public function afterAction($action, $result)
		{
			unset($this->get);
			unset($this->param);
			unset($this->page);

			return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
		}

		public function getClientId()
		{
			return \Yii::$app->getRequest()->getHeaders()->get('X-Client-Id', '');
		}
	}